STORAGE_KEY_BASE = 'express-dropbox-auth-'

module.exports =
  HTTP_CODE_UNAUTHORIZED: 401
  HTTP_CODE_INTERNAL_SERVER_ERROR: 500
  STORAGE_KEY_STATE: STORAGE_KEY_BASE + 'state'
  STORAGE_KEY_TOKEN: STORAGE_KEY_BASE + 'code'
